# main text of home
name: Shantanu Joshi
bio: 'I like data and penguins and quadcopters and keyboards and diving'

# twitter summary info
description: Shantanu's blog

# if it's an external image, update below for true
# better with square images
external-image: false
picture: 'assets/images/profile.jpeg'

url: https://shantanujoshi.github.io

permalink: /:title/

markdown: kramdown
highlighter: rouge

analytics-google: 'UA-82045037-1'
disqus: false

#facebook: myfacebook
# google: mygoogle
instagram: theshantanujoshi
# pinterest: mypinterest
linkedin: shantanu-joshi
github: shantanujoshi
#medium: medium
#vimeo: myvimeo
email: theshantanujoshi@gmail.com
twitter: shantanu_joshi_


authors:
    shantanujoshi:
        name: Shantanu Joshi
        bio: 'This page is scary...'
        external-image: false
        picture: assets/images/doge.jpg
        twitter: theshantanujosh.list .item
    

# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# paginate: 5
# paginate_path: "blog/:num/"

projects: true

about: false
blog: true

read-time: true

show-tags: true

related: true

blog-nav-links: false

show-author: true

animation: true

sass:
    sass_dir: _sass
    style: :compressed

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://shantanujoshi.github.io

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh, tasks]
